/*
 * File generated by Interface generator (dotup.dotup-vscode-interface-generator)
 * Date: 2019-12-10 01:33:21 
*/
import { Injectable } from "@angular/core";
import { TypeAheadResponsse } from "./typeaheadresponse";
import { HttpClient } from "@angular/common/http";
import { Observable } from "rxjs";
import { environment } from "src/environments/environment";

export interface ITypeAheadService {
    words: any;
    getTermExpandObs(word: String): Observable<TypeAheadResponsse>;
}
